// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSSCaRsz29V51tMEx0-a9EubY-X2-lf6s',
    appId: '1:57995396:web:f0cde058ef53721c4ed2d1',
    messagingSenderId: '57995396',
    projectId: 'all-in-one-cf264',
    authDomain: 'all-in-one-cf264.firebaseapp.com',
    storageBucket: 'all-in-one-cf264.appspot.com',
    measurementId: 'G-RE0XF5RTGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjHiB85B_uFPf9qIDXEOTgamTc-Jw3TVo',
    appId: '1:57995396:android:09ce70b8f3812c934ed2d1',
    messagingSenderId: '57995396',
    projectId: 'all-in-one-cf264',
    storageBucket: 'all-in-one-cf264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDV3YASV7tWowEeAawAjgCovfVVipIdY',
    appId: '1:57995396:ios:b95316dbb03e80394ed2d1',
    messagingSenderId: '57995396',
    projectId: 'all-in-one-cf264',
    storageBucket: 'all-in-one-cf264.appspot.com',
    iosBundleId: 'com.example.allInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZDV3YASV7tWowEeAawAjgCovfVVipIdY',
    appId: '1:57995396:ios:de3ef5831cc058d44ed2d1',
    messagingSenderId: '57995396',
    projectId: 'all-in-one-cf264',
    storageBucket: 'all-in-one-cf264.appspot.com',
    iosBundleId: 'com.example.allInOne.RunnerTests',
  );
}
