// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4MdixX2jeOZnGgobEMXk9Ml30yzd7LFc',
    appId: '1:270259997268:web:12c2ff2cb6c5db5917fbc1',
    messagingSenderId: '270259997268',
    projectId: 'all-in-one-ea1b2',
    authDomain: 'all-in-one-ea1b2.firebaseapp.com',
    storageBucket: 'all-in-one-ea1b2.appspot.com',
    measurementId: 'G-DRB14D5WC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75g6Tnmnfrvc4C013zW2vTnyps-rSxTA',
    appId: '1:270259997268:android:9dde6cec2d2c8e2917fbc1',
    messagingSenderId: '270259997268',
    projectId: 'all-in-one-ea1b2',
    storageBucket: 'all-in-one-ea1b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ68zOeXdjdmNEI6SQgoMJFr7MzuvAX-c',
    appId: '1:270259997268:ios:7f70b468716f181317fbc1',
    messagingSenderId: '270259997268',
    projectId: 'all-in-one-ea1b2',
    storageBucket: 'all-in-one-ea1b2.appspot.com',
    iosBundleId: 'com.example.allInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ68zOeXdjdmNEI6SQgoMJFr7MzuvAX-c',
    appId: '1:270259997268:ios:8940e19b1b29de6517fbc1',
    messagingSenderId: '270259997268',
    projectId: 'all-in-one-ea1b2',
    storageBucket: 'all-in-one-ea1b2.appspot.com',
    iosBundleId: 'com.example.allInOne.RunnerTests',
  );
}
